# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraftVersion = 1.21.1
yarnMappings = 1.21.1+build.3
loaderVersion = 0.16.2

# Fabric Dependencies
fabricVersion = 0.102.1+1.21.1

# Mod Properties
modId = coroutil
modName = CoroUtil
modVersion = 1.21.1-1.3.8
modDescription = Utility library for Corosus mods, providing common functionality and features. (modified)
mavenGroup = com.corosus.coroutil
archivesBaseName = coroutil
modAuthors = Corosus
modLicense = All Rights Reserved
